### ISSUE TITLE
[Todo] 탭 구성에 관한 절충안

### ISSUE THREAD

**Issue by estrella-kim** [estrella-works/fma_semas#12]
탭을 구성하는 데 있어서 탭 컨텐트 버튼탭, 컨텐트탭 따로 마크업을 구성하는 경우, js에서 eq를 부여하는 것도 방안이 됩니다. 
탭 컨텐트 버튼탭, 컨텐트탭을 하나로 구성한다면 버튼탭을 따로 absolute로 탭컨텐트는 relative로 수정하는 것도 반응형을 고려해서도 더 좋은 방향이 됩니다.

**Comment by MartinYounghoonKim** [comment]
오히려 탭 버튼과 그에 해당하는 컨텐츠를 구성하는 경우 버튼탭만 따로 abolute를 이용하여 레이아웃을 잡는 것은 오히려 반응형 부분에서는 오히려 단점만 될 수 있습니다. 

오히려 그렇게 잡는 경우에 PC형만 지원하는 경우에 하위 contents 영역이 가변적으로 늘어날 수 있다는 점에서는 득이 될 수 있으나, Mobile에서는 오히려 득보다는 실이 많을 수 있습니다. 또한 아직은 IE 호환성에 대한 부분 역시 배제하면 안되는 부분이 있어 CSS3 사용에 상대적으로 제한이 많이 될 수 있습니다.

그런 경우에는 차라리 Tab과 Contents를 Markup 상 분리를 시키는 것이 좋을 것 같습니다.
