### ISSUE TITLE
[Todo] 탭 스타일 부여에 대한 절충안

### ISSUE THREAD

**Issue by estrella-kim** [estrella-works/fma_semas#13]
탭 스타일에 관해서 탭에 class를 따로 부여하여 관리해주는 것이 좋습니다. 
예시) .tab01.have-tab3 혹은  .tab01.have-tab4

**Comment by MartinYounghoonKim** [comment]
이부분에 대한 것은 Tab의 경우 Tab이 스타일이 같으나, Tab의 갯수가 3개일지 4개일지 그 확장성을 고려한다면 예시에서 제공한 것과 같이 해당 탭에 해당하는 class를 부여하는 것이 좋을 것 같습니다.

**Comment by estrella-kim** [comment]
기본적인 tab 스타일에 베이직한 클래스를 부여하고 탭개수에  따른 스타일을 따른 클래스를 따로 부여하는 것으로 수정했습니다.
