### ISSUE TITLE
[Todo] 공통 타이틀에 대한 절충안

### ISSUE THREAD

**Issue by estrella-kim** [estrella-works/fma_semas#15]
공통 타이틀에는 클래스를 부여하고 모듈화하여 관리하는 게 좋습니다. 
이 때, 타이틀에 들어가는 이미지에 background-image 속성을 부여하는 것보다 image 태그를  사용하는 게 좋습니다.

**Comment by MartinYounghoonKim** [comment]
현재 디자인 상으로 보았을 경우, 각 타이틀이 Design에 따라 간격이나 size가 조금씩 다를 수 있으나, 의미적으로 봤을 때나 디자인의 flow를 봤을 경우에는 의도된 Design적인 요소는 아닌 듯 합니다.

오히려 이 부분에 대한 것은 코드의 재활용성 및 유지 운영적인 요소를 본다면 하나로 통일 하여 해당하는 것이 좋을 듯합니다.

**Comment by estrella-kim** [comment]
일괄적으로 동일한 타이틀을 부여하여 수정했습니다.
