### ISSUE TITLE
[HotFix]html5 스크립트 위치 변경 

### ISSUE THREAD

**Issue by MartinYounghoonKim** [estrella-works/fma_semas#2]
[if lt IE 9]>
	﻿<script src="js/html5.js"></script>
<![endif]

위의 태그는 ie6-8 에서 html5 태그들을 사용할 수 있게 도와주는 플러그인입니다.
위 스크립트는 head 태그 안에 위치하는 게 조금 더 맞을듯 합니다.

[참고]: https://github.com/afarkas/html5shiv

**Comment by estrella-kim** [comment]
IE 조건부 주석의 위치를  head 태그 안으로 변경했습니다.
