### ISSUE TITLE
[Todo]서브페이지 마크업 수정

### ISSUE THREAD

**Issue by estrella-kim** [estrella-works/fma_semas#6]
서브페이지(화재공제|가입절차) 의 탭컨텐트 부분의 마크업을 수정해야합니다. 
현재의 마크업은 html 코드는 비교적 적지만,  1. 스크립트로 제어해야하는 요소가 늘어나며, 2. 클라이언트 측에서 수정하기가 비교적 까다로울 것 같습니다.

**Comment by MartinYounghoonKim** [comment]
이 부분에 대해서는 구두로 말씀 드린대로, 컨텐츠 단위로 묶는 게 어떻게 싶습니다.

접근성적인 부분도 그렇고, 무엇보다 기본적인 탭의 경우에는 시멘틱 마크업에 대한 부분도 생각외로 이슈가 되는 부분이 있습니다.

이부분은 확인 후, 수정 부탁드립니다.

**Comment by estrella-kim** [comment]
논의했던 대로 컨텐츠 단위로 묶어 마크업과 스타일 수정 완료했습니다.
